include: package:flutter_lints/flutter.yaml

# Temporarily relax a few noisy rules so analyzer runs cleanly in CI/local
linter:
  rules:
    avoid_print: false
    use_build_context_synchronously: false
    unnecessary_brace_in_string_interps: false
    prefer_const_constructors: false
    prefer_const_declarations: false
    avoid_relative_lib_imports: false
